Repository tractorcow-farm/silverstripe-fluent, pull requests merged in 2018-09, with the labels that each got.

#459 3.8: Make Fluent compatible to SilverStripe 3.7.x / PHP 7.2
  _config.php
  code/Fluent.php
Labels: affects/v3

#460 FIX Text collector translations now compile without errors
  lang/en.yml
  src/Model/Locale.php
Labels: affects/v4, change/patch

#445 v4: Proposal to add config setting for CMS publish required.
  _config/model.yml
  src/Extension/FluentExtension.php
  tests/php/Extension/FluentSiteTreeExtensionTest.php
Labels: affects/v4, change/minor

#463 v4: Added config setting to bypass filtered locale logic in stage. Fixes #461
  _config/model.yml
  src/Extension/FluentFilteredExtension.php
  tests/php/Extension/FluentFilteredExtensionTest.php
Labels: affects/v4, change/patch

#464 ENHANCEMENT: Update unit tests to use withState where appropriate. Resolves #462
  tests/php/Extension/FluentBadgeExtensionTest.php
  tests/php/Extension/FluentExtensionTest.php
  tests/php/Extension/FluentFilteredExtensionTest.php
  tests/php/Extension/FluentSiteTreeExtensionTest.php
  tests/php/Extension/FluentVersionedExtensionTest.php
  tests/php/Middleware/DetectLocaleMiddlewareTest.php
Labels: affects/v4, change/minor

#469 FIX Performance update - reduces the use of filter on multiple subsequent calls to getByLocale
  src/Model/Locale.php
Labels: affects/v4, change/patch

#468 FIX Opt-in performance fix for many consecutive lookups using isLocalisedInStage
  src/Extension/FluentVersionedExtension.php
  tests/php/Extension/FluentVersionedExtensionTest.php
Labels: affects/v4, change/patch

#473 Exclude sorting tests from Travis builds and clear static locale cache in tests
  .travis.yml
  src/Model/CachableModel.php
  tests/php/Extension/FluentExtensionTest.php
Labels: affects/v4, change/patch

#472 FIX ReadVersions GraphQL operation now has the current fluent locale added as a filter
  _config/cms.yml
  src/Extension/FluentReadVersionsExtension.php
  tests/php/Extension/FluentReadVersionsExtensionTest.php
Labels: affects/v4, change/patch

#442 Opt-out of cookie and session locale persistence (fixes #440)
  docs/en/configuration.md
  src/Middleware/DetectLocaleMiddleware.php
  tests/php/Middleware/DetectLocaleMiddlewareTest.php
Labels: affects/v4, change/patch
