Repository tractorcow-farm/silverstripe-fluent, pull requests merged in 2018-08, with the labels that each got.

#450 Fix deprecated filter method in SearchVariant
  src/Search/FluentSearchVariant.php
Labels: affects/v4, change/patch, impact/low

#451 FIX Ensure alterQuery is compatible with silverstripe/fulltextsearch <3.3
  src/Search/FluentSearchVariant.php
Labels: affects/v4, change/patch

#453 Can now translate Locales tab added by FluentFilteredExtension, da.yml
  lang/da.yml
  lang/en.yml
  src/Extension/FluentFilteredExtension.php
Labels: affects/v4, change/patch

#452 [FIX] Ensure the default locale is set correctly for domain based configuration
  src/Extension/FluentDirectorExtension.php
Labels: affects/v4, change/patch

#443 v4: ENHANCEMENT Update CMS localisation status messages.
  src/Extension/FluentSiteTreeExtension.php
  src/Model/FallbackLocale.php
  tests/php/Extension/FluentSiteTreeExtensionTest.php
Labels: affects/v4, change/minor

#457 Fix bad xml in GoogleSitemapController_sitemap.ss
  templates/Wilr/GoogleSitemaps/Control/GoogleSitemapController_sitemap.ss
Labels: affects/v4, change/patch
