Repository tractorcow-farm/silverstripe-fluent, pull requests merged in 2018-04, with the labels that each got.

#393 Update composer requirement constraints
  composer.json
Labels: affects/v4, change/patch

#395 Added docs for frontend_publish_required. Updated Locale docblock
  docs/en/configuration.md
  src/Model/Locale.php
Labels: affects/v4, change/patch, type/docs

#396 Change getLocalisedTables method to public.
  src/Extension/FluentExtension.php
Labels: affects/v4, change/minor

#397 Added some scenarios to documentation
  docs/en/scenarios.md
  readme.md
Labels: affects/v4, type/docs

#407 ENHANCEMENT Allow frontend publish filter to be disabled via yml
  _config.php
  src/Extension/FluentExtension.php
Labels: affects/v4, change/minor
