Repository tractorcow-farm/silverstripe-fluent, pull requests merged in 2018-03, with the labels that each got.

#370 Update documentation
  docs/en/configuration.md
  docs/en/how-fluent-works.md
  docs/en/installation.md
  readme.md
Labels: affects/v4, type/docs

#374 Allow cookie domain and path to be configurable
  src/Middleware/DetectLocaleMiddleware.php
Labels: affects/v4, change/minor, type/enhancement

#381 FIX Cast default locale title as a DBField to prevent search field scaffolding error
  src/Model/Domain.php
Labels: affects/v4, change/patch
