Repository tractorcow-farm/silverstripe-fluent, pull requests merged in 2018-02, with the labels that each got.

#345 DOCS Add explicit notes about using fluent with versioned DataObjects with example config
  docs/en/configuration.md
  docs/en/dataobjects.md
  docs/en/installation.md
Labels: affects/v4, type/docs

#346 NEW Use Bootstrap alert class in locale status message
  src/Extension/FluentSiteTreeExtension.php
Labels: affects/v4, change/minor, type/UX

#352 FIX Re-enable support for adding other locale links to Google sitemaps
  _config/priority.yml
  src/Extension/FluentDirectorExtension.php
  templates/FluentSitemapController_sitemap.ss
  templates/Wilr/GoogleSitemaps/Control/GoogleSitemapController_sitemap.ss
Labels: affects/v4

#355 Fix bug: removing the entire table.
  src/Extension/FluentExtension.php
Labels: affects/v4, change/patch, effort/easy, impact/critical, type/bug

#361 ENHANCEMENT Update bootstrap alert
  lang/en.yml
  src/Extension/FluentSiteTreeExtension.php
Labels: affects/v4, impact/low, type/UX, type/enhancement

#359 ENHANCEMENT Support fulltext search per locale
  src/Search/FluentSearchVariant.php
Labels: affects/v4, change/minor, effort/hard, impact/high, type/enhancement

#362 NEW Add Fluent locale states as badges in CMS breadcrumbs
  _config/cms.yml
  client/dist/styles/fluent.css
  client/src/styles/fluent.scss
  src/Extension/FluentBadgeExtension.php
  src/Extension/FluentExtension.php
  src/Extension/FluentVersionedExtension.php
  src/Model/Locale.php
  tests/php/Extension/FluentBadgeExtensionTest.php
  tests/php/Extension/FluentBadgeExtensionTest.yml
  tests/php/Extension/FluentSiteTreeExtensionTest.php
  tests/php/Extension/FluentVersionedExtensionTest.php
  tests/php/Extension/Stub/FluentStubController.php
  tests/php/Model/LocaleTest.php
Labels: affects/v4, type/UX, type/enhancement

#366 ENHANCEMENT Add fluent icon to translatable fields
  client/dist/styles/fluent.css
  client/dist/styles/fluent.css.map
  client/src/styles/fluent.scss
  lang/en.yml
  src/Extension/FluentExtension.php
  src/Extension/FluentSiteTreeExtension.php
Labels: affects/v4, type/UX, type/enhancement
