Repository tractorcow-farm/silverstripe-fluent, pull requests merged in 2020-07, with the labels that each got.

#631 BUG fix issue with member permissions erroring before fluent state is initialised
  src/Extension/FluentMemberExtension.php
Labels: affects/v5, change/patch

#627 NEW: Localisation manager UI improvements.
  src/Extension/FluentExtension.php
  src/Extension/FluentSiteTreeExtension.php
  src/Extension/FluentVersionedExtension.php
  src/Extension/Traits/FluentAdminTrait.php
  src/Extension/Traits/FluentBadgeTrait.php
  src/Model/RecordLocale.php
  src/View/FluentTemplateGlobalProvider.php
  tests/php/Extension/FluentBadgeExtensionTest.php
  tests/php/Extension/FluentSiteTreeExtensionTest.php
Labels: affects/v5, effort/medium, impact/high, type/enhancement, type/wip

#632 NEW: Localised copy
  docs/en/localised-copy.md
  readme.md
  src/Extension/FluentExtension.php
  tests/php/Extension/LocalisedCopyTest/Animal.php
  tests/php/Extension/LocalisedCopyTest/DuplicationTest.php
  tests/php/Extension/LocalisedCopyTest/DuplicationTest.yml
  tests/php/Extension/LocalisedCopyTest/Horse.php
  tests/php/Extension/LocalisedCopyTest/Saddle.php
  tests/php/Extension/LocalisedCopyTest/Steed.php
  tests/php/Extension/LocalisedCopyTest/Tail.php
Labels: affects/v5

#635 Source locale lookup correction.
  src/Extension/FluentExtension.php
Labels: affects/v5

#636 Encoding configuration documentation.
  docs/en/configuration.md
Labels: affects/v5, effort/easy, type/docs

#638 Site Tree status flags localised.
  src/Extension/FluentSiteTreeExtension.php
Labels: affects/v5
